import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import ToastNotification from "./components/ui/ToastNotification";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CashTrackr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ToastNotification />
        {children}
      </body>
    </html>
  );
}
